# Teardown preview page on close pull request 

name: electron-brain-preview
on: 
  pull_request:
      types: [closed]

jobs:
  surge-teardown:
    runs-on: ubuntu-latest
    steps:
      - name: teardown
        uses: adrianjost/actions-surge.sh-teardown@master
        with:
          regex: '${{github.repository_owner}}-${{github.workflow}}-${{github.head_ref}}'
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}