# Dispatch pull request event to PTR-KLK/electron-brain repository and add comment with url

name: electron-brain-preview
on: 
  pull_request:
      types: [opened, synchronize]

jobs:

  dispatch:
    name: Dispatch preview-note event
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: PTR-KLK/electron-brain
          event-type: preview-note
          client-payload: '{"repository_owner": "${{ github.repository_owner }}", "workflow": "${{ github.workflow }}", "head_ref": "${{github.head_ref}}", "run_number: "${{ github.run_number }}"}'

  comment:
    name: Comment a pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Comment a pull_request
        uses: mb2dev/github-action-comment-pull-request@1.0.0
        with:
          message: |
            Preview available (soon) at:
            [Preview URL](https://${{github.repository_owner}}-${{github.workflow}}-${{github.head_ref}}-run-${{github.run_number}}.surge.sh)
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}